apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.service.port }}
    - name: https
      port: 443
      protocol: TCP
      targetPort: {{ .Values.service.port }}
