namespace: dev
appName: reverse-ip-service
replicaCount: 1

image:
  repository: 097267457133.dkr.ecr.eu-central-1.amazonaws.com/reverse-ip-service
  imagePullPolicy: Always
  tag: "latest"

serviceAccount:
  create: true
  annotations:
    arn: arn:aws:iam::097267457133:role/marcus-eks-cluster-reverse-ip-service-oidc

service:
  port: 5678
  type: ClusterIP
  externalTrafficPolicy: Local

ingress:
  enabled: true
  className: ""
  host: demo.marcdomain.dev
  pathType: ImplementationSpecific
  path: /
  servicePort: 5678

  tls: []

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 1000m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
